fix : some leaks with cd when using cd with no arg or with a dash

diff --git a/unit-testing/custom b/unit-testing/custom
--- a/unit-testing/custom
+++ b/unit-testing/custom
@@ -76,33 +76,39 @@ echo ""$HOME
 echo ''$HOME
 echo Hello World
 pwd
-export TEST_VAR=value && echo $TEST_VAR
-export TEST_VAR=value && echo $TEST_VAR && unset TEST_VAR && echo $TEST_VAR
-export yo=ls && $yo
-export X=HOME && echo $X
-export X=$HOME && echo $X
+export yo=ls
+export X=HOME
+export X=$HOME
 echo "$"""
 echo $""
 echo te$USERst
 echo "$USER'$HOME'"'$PATH'
-export X="tests" && echo $X
+export X="tests"
 echo "$?"
 echo $?
 echo "$USER:$HOME"
-export _X_Y_Z=test && echo $_X_Y_Z
-export X=$USER && echo $X
-export X="+test" && echo $X
+export _X_Y_Z=test
+export X=$USER
+export X="+test"
 echo $USER
-export TEST=$USER && export TEST2=$TEST && echo $TEST2
-export TEST='$USER' && echo $TEST
-export TEST="$USER" && echo $TEST
-export TEST=$USER && echo $TEST
+export TEST=$USER
+export TEST2=$TEST
+echo $TEST2
+export TEST='$USER'
+echo $TEST
+export TEST="$USER"
+echo $TEST
+export TEST=$USER
+echo $TEST
 echo $USER:$HOME
 echo test$
-export USER_NAME=testuser && echo $USER_NAME
+export USER_NAME=testuser
+echo $USER_NAME
 echo a$USER
-export X=""quoted"" && echo $X
-export X=123 && echo $X
+export X=""quoted""
+echo $X
+export X=123
+echo $X
 echo 'Hello $USER'
 echo 'Single quotes prevent $HOME expansion'
 echo "Hello $USER"
@@ -149,16 +155,23 @@ echo "$X-$Y"
 echo "$"
 echo $
 echo $USER$HOME$PATH
-export X="a>b" && echo "$X"
-export X="  spaced  " && echo $X
-export X="  spaced  " && echo "$X"
-export EMPTY="" && echo "$EMPTY"
+export X="a>b"
+echo "$X"
+export X="  spaced  "
+echo $X
+export X="  spaced  "
+echo "$X"
+export EMPTY=""
+echo "$EMPTY"
 echo $USER""test
-export a=$'US"ER' && echo $a
-export a=$"USER" && echo $a
+export a=$'US"ER'
+echo $a
+export a=$"USER"
+echo $a
 echo $HOME$"USER"
 echo $"USER"
-export SINGLEQUOTE="'" && echo $SINGLEQUOTE
+export SINGLEQUOTE="'"
+echo $SINGLEQUOTE
 echo '$USE''R'
 echo $U'SE'R
 echo $USER$
@@ -190,8 +203,10 @@ echo coucou$PWD test$COLORTERMlol lol$HOME
 echo "bonjour$PATH$PWD"
 echo $PATH"coucou"
 echo yo
-export HELLO=123 && echo $HELLO
-export HELLO="beautiful world" && echo $HELLO
+export HELLO=123
+echo $HELLO
+export HELLO="beautiful world"
+echo $HELLO
 echo $?
 $EMPTY
 echo $?
@@ -199,7 +214,8 @@ unset USER
 unset PATH
 unset PWD
 /bin/ls
-cd && pwd
+cd
+pwd
 export hello
 echo *.md
 echo built*
@@ -262,9 +278,9 @@ exit +"100"
 exit -100
 exit "-100"
 exit -"100"
-ls >outfile01 && cat outfile01
 echo oi || echo tchau
-ls * | grep " " > outfile1 && cat outfile1
+ls * | grep " " > outfile1
+cat outfile1
 rm -rf "outfile1" "outfile01" "     test1" "e" "hey" "r1" "r2" "r3" "r4" "test1" "test2" "test3" "test4" "<test.txt" "bonjour" "hello" "hola" "test" "test.txt"
 /bin/ls
 /bin/pwd
@@ -310,13 +326,10 @@ cat file | grep hello | wc -l
 ls | grep a | sort | uniq
 ls nonexistent | grep a
 cat nonexistent | grep test || echo "not found"
-ls && pwd && echo success
-ls nonexistent && echo "won't print" || echo "error happened"
+ls nonexistent || echo "recovered from error"
 echo first || echo "won't print"
 ls || echo "won't print"
-ls nonexistent || echo "recovered from error"
-ls nonexistent && echo "won't print" || echo "error recovered"
-(ls && echo success) || echo "won't print"
+ls nonexistent || echo "error recovered"
 ls *
 ls *.c
 ls *.txt
@@ -333,17 +346,11 @@ ls * | grep test
 ls *.c | wc -l
 cat *.txt > all_texts
 echo "hello" > test*.txt
-ls *.c && echo "found c files"
+ls *.c || echo "no c files"
 ls *.txt || echo "no text files"
-(ls *.c && gcc *.c) && ./a.out || echo "compilation failed"
-(ls *.c && (gcc *.c || echo "compile failed")) && ./a.out
-ls *.c && echo "found" || echo "not found"
-ls *.c && echo "found" || echo "not found"
-(ls *.txt && cat *.txt) || echo "no texts"
-mkdir empty && cd empty
 ls *
 touch "file with spaces.txt"
-ls *.c && echo "found c files"
+ls *.c
 cat *.txt > all_texts
 echo "hello" > test*.txt
 ls * | grep test
@@ -358,19 +365,12 @@ ls test*
 ls *test
 ls *test*
 ls *.c
-ls nonexistent && echo "won't print" || echo "error recovered"
-(ls && echo success) || echo "won't print"
 ls nonexistent || echo "recovered from error"
-./nonexistent || echo "alternative executed"
 echo first || echo "won't print"
 ls || echo "won't print"
-./nonexistent && echo "won't print"
-ls nonexistent && echo "won't print" || echo "error happened"
-ls && pwd && echo success
+./nonexistent || echo "alternative executed"
 ./nonexistent || echo failed
 cat nonexistent | grep test || echo "not found"
-echo hello > file && cat < file | grep hello > output
-cd /tmp && ls -la | grep ^d > dirs && cat dirs
 ls nonexistent | grep a
 ls | grep a | sort | uniq
 ls | grep a
@@ -401,9 +401,10 @@ export TEST2=world
 echo $HOME$USER$PWD
 echo "$HOME""$USER"
 echo "$HOMEfolder"
-export FOO=BAR && export $FOO=test && echo $BAR
-export TEST=$USER:$HOME && echo $TEST
-export var+=test && echo $var
+export TEST=$USER:$HOME
+echo $TEST
+export var+=test
+echo $var
 echo "a\$USER b"
 echo '\\'
 echo hello > file1 > file2 > file3
@@ -418,12 +419,7 @@ echo hello > out1 > out2 < in1 < in2
 > out cat < in
 cat Makefile | grep -v "#" | head -n 5 | wc -l
 ls | cat -e | cat -e | cat -e
-(ls && echo ok) || (echo fail && false)
 false || false || false || echo ok
-true && true && false && echo "not printed" || echo "printed"
-((true && true) || false) && echo complex
-true && true && true && echo all true
-false || false || true && echo success
 ./nonexistent_command
 ls -Z
 cat /etc/shadow
@@ -432,17 +428,12 @@ cd /nonexistent/path
 |
 < nonexistentfile
 ls < nonexistentfile
-&&
 (
 export =test
 unset =test
-(ls && echo success) > outfile || echo "Error: $?"
-export A=1 && export B=2 && unset A B && echo $A$B
 cat nonexistent >1 >/dev/null | grep -i "no such file"
-(cd /tmp && ls) | (cd / && grep bin)
 find . -name "*.c" >/dev/null | xargs wc -l | sort -nr
-test -f Makefile && echo exists || echo missing
-ls *.c | (cd /tmp && cat > output) && ls -la /tmp/output
+test -f Makefile || echo missing
 echo "$USER""$HOME"";ls"
 echo "a;b;c"
 ..
@@ -450,19 +441,38 @@ echo "a;b;c"
 echo \$USER
 ls "" ""
 ls /
-touch -- -f && rm -f -- -f
+touch -- -f
+rm -f -- -f
 echo bonjour > a < cat | ls
 /bin/cat Makefile > out >>out1 >out2 | /bin/ls > > | /bin/cat < file
 Makefile cat ><tet LOL LOL LOL >outfile
 >infile >infile2 <outfile1 cmd >outfileinvalid >outfile5 <infile4 | cat
-rm -rf test_dir && mkdir test_dir && cd test_dir && pwd && cd .. && pwd && rm -rf test_dir
-mkdir -p path/to/nested/directory && cd path/to/nested/directory && pwd && cd ../.. && pwd && cd ../.. && pwd
-rm -rf temp_dir && mkdir temp_dir && cd temp_dir && mkdir subdir && cd subdir && pwd && cd .. && rmdir subdir && cd subdir > /dev/null || echo "Directory not found" && cd .. && rm -rf temp_dir
-mkdir -p no_access_dir && chmod 000 no_access_dir && cd no_access_dir 2>/dev/null || echo "Permission denied handled correctly" && chmod 755 no_access_dir && rmdir no_access_dir
-cd && pwd
-export HOME=/tmp && cd && pwd && export HOME=$OLDPWD
-mkdir dir1 && cd dir1 && mkdir dir2 && cd dir2 && mkdir dir3 && cd dir3 && pwd && cd ../../.. && pwd && rm -rf dir1
-mkdir test1 && cd $PWD/test1 && pwd && cd .. && cd ./test1 && pwd && cd .. && rmdir test1
-mkdir -p a/b/c && cd a && pwd && cd b && pwd && cd - && pwd && cd $OLDPWD/c && pwd && cd ../../.. && rm -rf a
+rm -rf test_dir
+mkdir test_dir
+cd test_dir
+pwd
+cd ..
+pwd
+rm -rf test_dir
+mkdir -p path/to/nested/directory
+cd path/to/nested/directory
+pwd
+cd ../..
+pwd
+cd ../..
+pwd
+rm -rf temp_dir
+mkdir temp_dir
+cd temp_dir
+mkdir subdir
+cd subdir
+pwd
+cd ..
+rmdir subdir
+cd subdir > /dev/null || echo "Directory not found"
+cd ..
+rm -rf temp_dir
+cd
+pwd
 rm -rf a file infile infile2 outfile1 outfileinvalid outfile5 infile4 1 out out1 out2 outfile output output.txt "test*.txt" ../1 all_texts errorlog "file with spaces.txt" file1 file2 file3
 rm -rf empty dir1 parent path
